const DEV_TWEETS = {
  FETCH: 'FETCH_DEV_TWEETS',
  FETCH_SUCCESS: 'DEV_TWEETS_FETCH_SUCCESS',
  FETCH_FAIL: 'DEV_TWEETS_FETCH_FAIL'
};
const NOTIFIER = { REMOVE: 'REMOVE_NOTIFIER' };

export { DEV_TWEETS, NOTIFIER };
